name 'my_minecraft_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures minecraft_server'
long_description 'Installs/Configures minecraft_server'
version '0.1.0'

depends 'base-server'
depends 'java'
depends 'minecraft', '~> 0.5.2'
